<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPwel4GV\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPwel4GV/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPwel4GV.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPwel4GV\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPwel4GV\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Pwel4GV',
    'container.build_id' => '30bf7c4b',
    'container.build_time' => 1593610981,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPwel4GV');
