<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWuPQBvy\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWuPQBvy/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWuPQBvy.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWuPQBvy\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWuPQBvy\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WuPQBvy',
    'container.build_id' => '2fa0a3c0',
    'container.build_time' => 1593439036,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWuPQBvy');
